testup/config/routes.rb
Rails.application.routes.draw do
  resources :courses
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about/', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :exams
  resources :registered_exam
end

testup/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

testup/app/models/course.rb
class Course < ApplicationRecord
     has_and_belongs_to_many :users
     has_many :exams
     has_one :user, as: :teacher
end

testup/app/models/exam.rb
class Exam < ApplicationRecord
	belongs_to :course
end

testup/app/models/registered_exam.rb
class RegisteredExam < ApplicationRecord
  belongs_to :user
  belongs_to :exam
end

testup/app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :courses
  has_many :exams, :through => :courses
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password , presence: true, :on => :create, length: { minimum: 6 }
end

testup/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
    def signed_in_user
      unless signed_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

testup/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :is_teacher?, only: [:new, :create]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])
    session[:course_id] = @course.id
  end

  # GET /courses/new
  def new
    @course = Course.new
    @course.teacher = @curr_user.id
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    @course.teacher = @curr_user.id

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course }
        format.json { render :show, status: :created }
        if is_teacher?
          @curr_user.courses.push(@course)
        end
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      @course = Course.find(params[:id])
      if @course.update(course_params)
        format.html { redirect_to @course}
        format.json { render :show, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :user_ids => [])
    end
end

testup/app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :signed_in_user, only: :show
  before_action :teacher_user,   only: [:create, :destroy]

  def index
    @exams = Exam.all
  end

  def show
    @exam = Exam.find(params[:id])
  end

  def edit
  end

  def new
    @exam = Exam.new
  end

  def create
    @exam = Exam.new(exam_params)
    @exam.course = Course.find(session[:course_id])
    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam }
        format.json { render :show, status: :created }
        flash[:success] = "Exam created!"
      else
        render :new
      end
    end
  end


  def update
    respond_to do |format|
      @exam = Exam.find(params[:id])
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @exam = Exam.find(params[:id])
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url}
      format.json { head :no_content }
    end
  end

  private
    def exam_params
      params.require(:exam).permit(:date, :location, :seats)
    end

    def teacher_user
      redirect_to(root_url) unless curr_user.teacher?
    end
end

testup/app/controllers/registered_exam_controller.rb
class RegisteredExamController < ApplicationController

  def create
    @registered_exam = RegisteredExam.new
    @user = User.find(params[:user_id])
    @exam = Exam.find(params[:exam_id])
    @registered_exam.user = @user
    @registered_exam.exam = @exam
    @exam.decrement(:seats, 1)
    @exam.save
    @registered_exam.save
    RegisteredExamMailer.registered_exam_email(@user, @exam).deliver_later
    redirect_to @user
  end

  def destroy
    @user = User.find(params[:user_id])
    @exam = Exam.find(params[:exam_id])
    @registered_exam = RegisteredExam.where(user_id: @user.id, exam_id: @exam.id)
    if @registered_exam.delete_all
      @exam.increment!(:seats)
      redirect_to user_path
    end
  end

end

testup/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    curr_user = User.find_by(email: params[:session][:email].downcase)
    if curr_user && curr_user.authenticate(params[:session][:password])
      sign_in curr_user
      redirect_to curr_user
    else
      flash.now[:danger] = 'Email, Password, or both are incorrect'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

testup/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

testup/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Thank you for joining TestUp!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

testup/app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis
  def display_title(page_title = '')
    base_title = "TestUp"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

testup/app/helpers/courses_helper.rb
module CoursesHelper
end

testup/app/helpers/exams_helper.rb
module ExamsHelper
end

testup/app/helpers/registered_exam_helper.rb
module RegisteredExamHelper
end

testup/app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session.delete(:user_id)
    @curr_user = nil
  end

  def curr_user
    if @curr_user.nil?
      @curr_user = User.find_by(id: session[:user_id])
    else
      @curr_user
    end
  end

  def is_teacher?
    curr_user.teacher == true
  end

  def is_student?
    curr_user.teacher == false
  end

  def signed_in?
    !curr_user.nil?
  end
end

testup/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

testup/app/helpers/users_helper.rb
module UsersHelper
end

testup/app/views/courses/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
<%= form_for(course) do |f| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <h5>Students</h5>
      <table class="table">
        <tr>
          <%= f.collection_check_boxes(:user_ids, User.all, :id, :name)%>
        </tr>
      </table>


  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>
</div>
</div>

testup/app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<% @course = Course.find(params[:id]) %>
<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

testup/app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table class="table">
  <thead>
    <tr>
      <th>Course Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

testup/app/views/courses/new.html.erb
<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

testup/app/views/courses/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

<p>
  <strong>Name:</strong>
  <%= @course.name %>
  <strong>Size:</strong>
  <%= @course.users.count %>
  <strong>Teacher:</strong>
  <%= @course.teacher %>
</p>

<p>
<strong>Students:</strong>
<% @course.users.each do |student| %>
  <p><%= student.name %></p>
<% end %>
</p>

<% if is_teacher? %>
    <%= button_to "New Exam", new_exam_path, method: :get, class: 'btn btn-primary'%>
<% end %>
</div>
</div>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

testup/app/views/exams/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
<%= form_for(exam) do |f| %>
    <% if exam.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

          <ul>
            <% exam.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="field">
      <%= f.label :date %>
      <%= f.datetime_select :date, :discard_seconds => true, ampm: true, :class => 'form-control'  %>
    </div>

    <div class="field">
      <%= f.label :location %>
      <%= f.text_field :location,  class: 'form-control' %>
    </div>

    <div class="field">
      <%= f.label :seats %>
      <%= f.text_field :seats,  class: 'form-control' %>
    </div>

    <div class="actions">
      <%= f.submit class: "btn btn-primary" %>
    </div>
<% end %>
</div>
</div>

testup/app/views/exams/edit.html.erb
<h1>Editing Exam</h1>

<% @exam = Exam.find(params[:id]) %>
<%= render 'form', exam: @exam %>

<%= link_to 'Show', @exam %> |
<%= link_to 'Back', exams_path %>

testup/app/views/exams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exams</h1>

<table class='table'>
  <thead>
  <tr>
    <th>Exam Name</th>
    <th>Time</th>
    <th>Location</th>
    <th>Seats</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% curr_user.exams.each do |exam| %>
      <tr>
        <td><%= exam.course.name %></td>
        <td><%= exam.date %></td>
        <td><%= exam.location %></td>
        <td><%= exam.seats %></td>
        <td><%= link_to 'Show', exam %></td>
        <td><%= link_to 'Edit', edit_exam_path(exam) %></td>
        <td><%= link_to 'Destroy', exam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

testup/app/views/exams/new.html.erb
<%= render 'form', exam: @exam %>

<%= link_to 'Back', courses_path %>

testup/app/views/exams/show.html.erb
<section>
  <p><strong>Test Info:</strong></p>
  <p>
    <strong>Course:</strong>
    <%= @exam.course.name %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= @exam.date %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= @exam.location %>
  </p>
</section>

<% if RegisteredExam.exists?(exam_id: @exam.id) %>
  <section>
  <p><strong>Registered Students:</strong></p>
  <% RegisteredExam.where(:exam_id => @exam.id).to_a.each do |r|  %>
    <ul>
      <li><%= r.user.name %></li>
    </ul>
  </section>
  <% end %>
<% end %>

<% if is_teacher? %>
  <%= link_to 'Edit', edit_exam_path(@exam) %> |
  <%= link_to 'Back', exams_path %>
<% else %>
  <%= link_to 'Back', curr_user %>
  <%= link_to 'Join', '#' %>
<% end %>

testup/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    TestUp
    by <a href="https://cryptic-taiga-13180.herokuapp.com/">Group 5</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

testup/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "testup", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <% if signed_in? %>
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <% if is_teacher? %>
                  <li><%= link_to "My Courses", courses_path %></li>
                  <li><%= link_to "My Exams", exams_path %></li>
                <% else %>
                  <li><%= link_to 'My Exams', curr_user %></li>
                <% end %>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
      <% else %>
        <li><%= link_to "Log in", login_path %></li>
      <% end %>
      </ul>
    </nav>
  </div>
</header>

testup/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

testup/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= display_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

testup/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_reason">
    <div class="alert alert-danger">
      The submission contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

testup/app/views/shared/_exam_form.html.erb
<%= form_for(@exam) do |f| %>
  <%= f.label :course %>
  <%= f.text_field :course, class: 'form-control' %>

  <%= f.label :location %>
  <%= f.email_field :location, class: 'form-control' %>

  <%= f.label :date %>
  <%= f.password_field :date, class: 'form-control' %>

  <%= f.label :time %>
  <%= f.password_field :time, class: 'form-control' %>

  <%= f.label :seats %>
  <%= f.password_field :time, class: 'form-control' %>

  <%= f.submit "Create an Exam", class: "btn btn-primary" %>
<% end %>

testup/app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  TestUp is an application to help teachers make it as easy as possible for students to register for exams
</p>

testup/app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

testup/app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  To get help with TestUp, see the FAQ section below,
  or contact us. We are always happy to help!
</p>

testup/app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to TestUp!</h1>

  <h2>
    Making Test Registration Simple
  </h2>

  <%= link_to "Join now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

testup/app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign Up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

testup/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %> -- Exams
      </h1>
    </section>
  </aside>

  <table class='table'>
    <thead>
    <tr>
      <th>Course</th>
      <th>Location</th>
      <th>Time</th>
      <th>Seats</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @user.exams.each do |exam| %>
      <tr>
        <td><%= exam.course.name %></td>
        <td><%= exam.location %></td>
        <td><%= exam.date %></td>
        <td><%= exam.seats %></td>
        <% if not is_teacher? %>
          <% if !RegisteredExam.exists?(user_id: @user.id, exam_id: exam.id) %>
            <td><%= button_to "Register", {:action => "create", :controller => "registered_exam", :user_id => @user.id, :exam_id => exam.id} %></td>
          <% else %>
            <td><%= button_to "Deregister", {:action => "destroy", :controller => "registered_exam", :user_id => @user.id, :exam_id => exam.id}, :method => :delete %></td>
          <% end %>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>